services:
  - type: web
    name: johan-corps-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: JohanCorps
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://johan-corps-backend.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/storage/database.sqlite
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_DRIVER
        value: sync
      - key: CORS_ALLOWED_ORIGINS
        value: https://johan-corps-frontend.vercel.app,https://johan-corps-frontend-4bqh63k2o-omfattendes-projects.vercel.app
      - key: SANCTUM_STATEFUL_DOMAINS
        value: johan-corps-frontend.vercel.app
    disk:
      name: sqlite-data
      mountPath: /var/www/storage
      sizeGB: 1
